import { env } from "@/lib/env";
import { createRepositoryIssue } from "@/lib/github/repositories";
import type { ScanSignal } from "@/lib/scanner/types";

export async function createImpactIssue(input: {
  installationId: number;
  owner: string;
  repo: string;
  changelogTitle: string;
  changelogUrl: string;
  summary: string;
  severity: "red" | "amber" | "green";
  migrationSteps: string[];
  signals: ScanSignal[];
}) {
  const body = renderIssueBody(input);

  return createRepositoryIssue({
    installationId: input.installationId,
    owner: input.owner,
    repo: input.repo,
    title: `[HubSpot changelog] ${input.changelogTitle}`,
    body,
    labels: [env.GITHUB_ISSUE_LABEL, `severity:${input.severity}`],
  });
}

function renderIssueBody(input: {
  changelogTitle: string;
  changelogUrl: string;
  summary: string;
  severity: "red" | "amber" | "green";
  migrationSteps: string[];
  signals: ScanSignal[];
}) {
  const signals = input.signals
    .map((signal) => `- \`${signal.filePath}\`: ${signal.label}`)
    .join("\n");
  const steps =
    input.migrationSteps.length > 0
      ? input.migrationSteps.map((step) => `- ${step}`).join("\n")
      : "- Review the linked changelog and confirm whether the detected usage needs migration.";

  return `## HubSpot changelog impact

**Severity:** ${input.severity}

**Changelog:** [${input.changelogTitle}](${input.changelogUrl})

${input.summary}

## Detected usage

${signals}

## Suggested migration steps

${steps}

Generated by Sprocky Changedust.`;
}
