import { env } from "@/lib/env";
import { createRepositoryIssue, getRepositoryDefaultBranch } from "@/lib/github/repositories";
import type { ScanSignal } from "@/lib/scanner/types";

export async function createImpactIssue(input: {
  installationId: number;
  owner: string;
  repo: string;
  changelogTitle: string;
  changelogUrl: string;
  summary: string;
  severity: "red" | "amber" | "green";
  migrationSteps: string[];
  signals: ScanSignal[];
}) {
  const defaultBranch = await getRepositoryDefaultBranch({
    installationId: input.installationId,
    owner: input.owner,
    repo: input.repo,
  }).catch(() => undefined);
  const body = renderIssueBody({
    ...input,
    defaultBranch,
  });

  return createRepositoryIssue({
    installationId: input.installationId,
    owner: input.owner,
    repo: input.repo,
    title: `[HubSpot changelog] ${input.changelogTitle}`,
    body,
    labels: [env.GITHUB_ISSUE_LABEL, `severity:${input.severity}`],
  });
}

function renderIssueBody(input: {
  owner: string;
  repo: string;
  defaultBranch?: string;
  changelogTitle: string;
  changelogUrl: string;
  summary: string;
  severity: "red" | "amber" | "green";
  migrationSteps: string[];
  signals: ScanSignal[];
}) {
  const signals =
    input.signals.length > 0
      ? input.signals
          .map((signal) => renderSignalReference(input, signal))
          .join("\n")
      : "- No repository-specific usage evidence is attached to this manual issue.";
  const steps =
    input.migrationSteps.length > 0
      ? input.migrationSteps.map((step) => `- ${step}`).join("\n")
      : "- Review the linked changelog and confirm whether the detected usage needs migration.";

  return `## HubSpot changelog impact

**Severity:** ${input.severity}

**Changelog:** [${input.changelogTitle}](${input.changelogUrl})

${input.summary}

## Detected usage

${signals}

## Suggested migration steps

${steps}

Generated by Sprocky Changedust.`;
}

function renderSignalReference(
  input: {
    owner: string;
    repo: string;
    defaultBranch?: string;
  },
  signal: ScanSignal,
) {
  const location = renderSignalLocation(input, signal);
  const excerpt = signal.excerpt ? `\n  - Evidence: \`${sanitizeEvidence(signal.excerpt)}\`` : "";

  return `- ${location}: ${signal.label}${excerpt}`;
}

function renderSignalLocation(
  input: {
    owner: string;
    repo: string;
    defaultBranch?: string;
  },
  signal: ScanSignal,
) {
  const label = signal.line ? `${signal.filePath}:${signal.line}` : signal.filePath;

  if (!input.defaultBranch) {
    return `\`${label}\``;
  }

  const encodedBranch = encodePath(input.defaultBranch);
  const encodedFilePath = encodePath(signal.filePath);
  const lineAnchor = signal.line ? `#L${signal.line}` : "";

  return `[${label}](https://github.com/${input.owner}/${input.repo}/blob/${encodedBranch}/${encodedFilePath}${lineAnchor})`;
}

function encodePath(value: string) {
  return value.split("/").map(encodeURIComponent).join("/");
}

function sanitizeEvidence(value: string) {
  return value.replaceAll("`", "'");
}
